<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Perscriptions", "Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Edit Perscriptions
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Perscriptions/save",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPerscDate" class="col-sm-2 control-label">Persc Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_date", "type" => "date", "class" => "form-control", "id" => "fieldPerscDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPerscJpeg" class="col-sm-2 control-label">Persc Of Jpeg</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_jpeg", "size" => 30, "class" => "form-control", "id" => "fieldPerscJpeg"]) ?>
    </div>
</div>


<?php echo $this->tag->hiddenField("id") ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
