<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search Perscriptions
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["Perscriptions/new", "Create Perscriptions"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "Perscriptions/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPerscId" class="col-sm-2 control-label">Persc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_id", "type" => "number", "class" => "form-control", "id" => "fieldPerscId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPerscDate" class="col-sm-2 control-label">Persc Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_date", "type" => "date", "class" => "form-control", "id" => "fieldPerscDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPerscJpeg" class="col-sm-2 control-label">Persc Of Jpeg</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_jpeg", "size" => 30, "class" => "form-control", "id" => "fieldPerscJpeg"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
