<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Customers/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["Customers/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Cust</th>
            <th>Cust Of First Of Name</th>
            <th>Cust Of Middle Of Name</th>
            <th>Cust Of Last Of Name</th>
            <th>Cust Of Date Of Of Of Birth</th>
            <th>Cust Of Gender</th>
            <th>Cust Of Address</th>
            <th>Cust Of Landline</th>
            <th>Cust Of Mobile</th>
            <th>Cust Of Insurance</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $Customer): ?>
            <tr>
                <td><?php echo $Customer->cust_id ?></td>
            <td><?php echo $Customer->cust_first_name ?></td>
            <td><?php echo $Customer->cust_middle_name ?></td>
            <td><?php echo $Customer->cust_last_name ?></td>
            <td><?php echo $Customer->cust_date_of_birth ?></td>
            <td><?php echo $Customer->cust_gender ?></td>
            <td><?php echo $Customer->cust_address ?></td>
            <td><?php echo $Customer->cust_landline ?></td>
            <td><?php echo $Customer->cust_mobile ?></td>
            <td><?php echo $Customer->cust_insurance_id ?></td>

                <td><?php echo $this->tag->linkTo(["Customers/edit/" . $Customer->cust_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["Customers/delete/" . $Customer->cust_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("Customers/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("Customers/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("Customers/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("Customers/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
