<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Doctor_Edu/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["Doctor_Edu/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Doc Of Edu</th>
            <th>Doc Of Medical Of Lic</th>
            <th>Doc Of University</th>
            <th>Doc Of Major</th>
            <th>Doc Of Degree</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $Doctor_Edu): ?>
            <tr>
                <td><?php echo $Doctor_Edu->doc_edu_id ?></td>
            <td><?php echo $Doctor_Edu->doc_medical_lic_id ?></td>
            <td><?php echo $Doctor_Edu->doc_university ?></td>
            <td><?php echo $Doctor_Edu->doc_major ?></td>
            <td><?php echo $Doctor_Edu->doc_degree ?></td>

                <td><?php echo $this->tag->linkTo(["Doctor_Edu/edit/" . $Doctor_Edu->doc_edu_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["Doctor_Edu/delete/" . $Doctor_Edu->doc_edu_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("Doctor_Edu/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("Doctor_Edu/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("Doctor_Edu/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("Doctor_Edu/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
