<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search Payments
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["Payments/new", "Create Payments"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "Payments/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPaymentId" class="col-sm-2 control-label">Payment</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["payment_id", "type" => "number", "class" => "form-control", "id" => "fieldPaymentId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPaymentDate" class="col-sm-2 control-label">Payment Of Date</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["payment_date", "type" => "date", "class" => "form-control", "id" => "fieldPaymentDate"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPaymentMethod" class="col-sm-2 control-label">Payment Of Method</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["payment_method", "size" => 30, "class" => "form-control", "id" => "fieldPaymentMethod"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPaymentAmount" class="col-sm-2 control-label">Payment Of Amount</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["payment_amount", "type" => "number", "class" => "form-control", "id" => "fieldPaymentAmount"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
