<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Drug_Suppliers", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Drug_Suppliers
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Drug_Suppliers/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldSupplierName" class="col-sm-2 control-label">Supplier Of Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["supplier_name", "size" => 30, "class" => "form-control", "id" => "fieldSupplierName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSupplierAddress" class="col-sm-2 control-label">Supplier Of Address</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["supplier_address", "size" => 30, "class" => "form-control", "id" => "fieldSupplierAddress"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSupplierLandline" class="col-sm-2 control-label">Supplier Of Landline</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["supplier_landline", "type" => "number", "class" => "form-control", "id" => "fieldSupplierLandline"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSupplierMobile" class="col-sm-2 control-label">Supplier Of Mobile</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["supplier_mobile", "type" => "number", "class" => "form-control", "id" => "fieldSupplierMobile"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
