<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Drug_Suppliers/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["Drug_Suppliers/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Supplier</th>
            <th>Supplier Of Name</th>
            <th>Supplier Of Address</th>
            <th>Supplier Of Landline</th>
            <th>Supplier Of Mobile</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $Drug_Supplier): ?>
            <tr>
                <td><?php echo $Drug_Supplier->supplier_id ?></td>
            <td><?php echo $Drug_Supplier->supplier_name ?></td>
            <td><?php echo $Drug_Supplier->supplier_address ?></td>
            <td><?php echo $Drug_Supplier->supplier_landline ?></td>
            <td><?php echo $Drug_Supplier->supplier_mobile ?></td>

                <td><?php echo $this->tag->linkTo(["Drug_Suppliers/edit/" . $Drug_Supplier->supplier_id, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["Drug_Suppliers/delete/" . $Drug_Supplier->supplier_id, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("Drug_Suppliers/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("Drug_Suppliers/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("Drug_Suppliers/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("Drug_Suppliers/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
