<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["Drugs_in_Perscription", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create Drugs_in_Perscription
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Drugs_in_Perscription/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldPerscId" class="col-sm-2 control-label">Persc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["persc_id", "type" => "number", "class" => "form-control", "id" => "fieldPerscId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDrugNdcId" class="col-sm-2 control-label">Drug Of Ndc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["drug_ndc_id", "type" => "number", "class" => "form-control", "id" => "fieldDrugNdcId"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
