<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search Drug_Couriers
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["Drug_Couriers/new", "Create Drug_Couriers"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "Drug_Couriers/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldDrugCourierId" class="col-sm-2 control-label">Drug Of Courier</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["drug_courier_id", "type" => "number", "class" => "form-control", "id" => "fieldDrugCourierId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDrugNdcId" class="col-sm-2 control-label">Drug Of Ndc</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["drug_ndc_id", "type" => "number", "class" => "form-control", "id" => "fieldDrugNdcId"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCourierId" class="col-sm-2 control-label">Courier</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["courier_id", "type" => "number", "class" => "form-control", "id" => "fieldCourierId"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
